#!/bin/bash

sxhkd -c $HOME/.config/berry/sxhkdrc &
picom -b --experimental-backend &
eww daemon & 
eww open -c ~/.config/eww/berry/bar/ bar

# Set decoration geometry
berryc border_width       2
berryc inner_border_width 5
berryc title_height       30
berryc edge_gap           66 10 10 10

# Set decoration colors
berryc focus_color         161616
berryc unfocus_color       292D3E
berryc inner_focus_color   F5F5F4
berryc inner_unfocus_color 73A5C6
berryc text_focus_color    161616
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Comic Mono:style=Bold:size=14"
