#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
eww daemon &
eww open -c ~/.config/eww/bspwm/bar/ bar& 

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         1
bspc config window_gap          12
bspc config active_border_color #A9B1D6
bspc config normal_border_color #0f0f14



bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a sxiv state=floating
bspc rule -a Sxiv state=floating
bspc rule -a scpad sticky=on state=floating rectangle=800x400+250+250
